[package]
authors = ["0xAlcibiades <alcibiades.eth@protonmail.com>"]
categories = ["mathematics"]
description = "Abstract algebraic structures for Rust"
homepage = "https://github.com/warlock-labs/noether"
keywords = ["math", "algebra", "scalar"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/warlock-labs/noether"
name = "noether"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.19"
cfg-if = "1.0"
paste = "1.0"

[features]
default = ["std"]
std = []
simd = ["std"]

[target.'cfg(target_arch = "aarch64")'.dependencies]
stdsimd = { version = "0.0.4", optional = true }

[lib]
